### ISSUE TITLE
Difficulté avec l'intégration de l'API Pronote

### ISSUE THREAD

**Issue by ns-bcr** [Merlode11/pronote-api#9]
Bonjour,

Je tiens tout d'abord à te remercier pour ton travail sur cette API, c'est exactement ce dont j'ai besoin pour mon projet. Cependant, je rencontre des difficultés à l'utiliser et à comprendre certaines parties (presque la totalité).

J'ai suivi la documentation et tenté plusieurs approches, mais je n'arrive pas à obtenir le résultat attendu. Je pense que je suis bloqué sur une mauvaise interprétation de certaines étapes. Je suis convaincu que votre API peut répondre à mes besoins, mais je ne sais pas comment m'y prendre pour avancer correctement.

Mon cas de ma région et celui de ac-dijon ou educonnect. J'ai essayé mais je n'arrive vraiment pas...

Je serais très reconnaissant si vous pouviez m'aider ou m'orienter pour résoudre mon problème.

Merci d'avance pour votre aide !

Cordialement,
Anas,

**Comment by Merlode11** [comment]
Bonjour !

Je vous en prie, moi je n'ai pas fait grand chose, j'ai juste fork le travail d'une autre personne que j'ai un peu complété.

Cependant, je n'ai plus trop le temps de m'en occuper puisque j'ai pas mal de choses à faire personnellement. 
Je vais voir ce que je peux faire pour vous aider mais malheureusement je ne vous promets rien...

Mais quel est votre problème plus exactement ? 
Que voulez-vous vous obtenir ?
Par quelles étapes passez vous jusqu'à obtenir une erreur ?

Bon courage !

**Comment by ns-bcr** [comment]
Bonsoir,

Merci infiniment d'avoir pris le temps de répondre ! Il est rare de voir des projets de ce type encore maintenus, et je tiens à saluer votre engagement.

Je dois avouer que je suis un peu perdu quant à l'utilisation de cette API. Mon objectif est d'extraire presque toutes les informations que Pronote met à disposition, dans le cadre d'un petit projet personnel auquel je tiens beaucoup.

Pour l'instant, j'ai réussi à communiquer avec Skolengo et à récupérer uniquement les quatre dernières notes, mais je n'ai pas pu aller plus loin. Je suis convaincu que votre API peut répondre à mes besoins, mais je ne sais pas comment avancer correctement, notamment pour me connecter à Pronote et accéder aux données.

Je comprends que vous ayez d'autres priorités personnelles, et je ne veux surtout pas vous mettre la pression. Prenez tout le temps nécessaire ; ce n'est pas urgent, même si je serais très heureux de réussir à mettre en place une connexion fonctionnelle et à récupérer les informations.

Encore une fois, merci pour votre aide précieuse. Je vous souhaite d'excellentes fêtes de fin d'année !

Cordialement,
Anas

**Comment by ns-bcr** [comment]
Alors voilà,  

J'ai essayé de trouver ce qui pourrait marcher, sauf que je tombe en permanence sur ce problème :  
```javascript
const pronote = require('pronote-api-maintained');

const url = 'XXXX';
const username = 'XXXX';
const password = 'XXXX';
const cas = 'ac-dijon';

async function main() {
    try {
        // Connexion à Pronote
        const session = await pronote.login(url, username, password, cas);

        console.log('Connecté à Pronote avec succès.');

        // Exemple : récupérer les notes et devoirs
        const marks = await session.marks(); 
        const homeworks = await session.homeworks(); 

        console.log('Notes:', marks);
        console.log('Devoirs:', homeworks);

        // Déconnexion
        session.logout();
    } catch (err) {
        console.error('Erreur lors de la connexion à Pronote :', err);
    }
}
main();
```

J'exécute avec `node app.js`, puis je reçois l'erreur suivante :  
```less
Erreur lors de la connexion à Pronote : Error: Cookie not in this host's domain. Cookie:"" Request:cas.eclat-bfc.fr
    at CookieJar.setCookie (node_modules/tough-cookie/lib/cookie.js:1195:15)
    at CookieJar.setCookie (node_modules/universalify/index.js:5:67)
    at axioRequest.js:54:17
    at Array.forEach (<anonymous>)
    at axioRequest.js:53:40
    at new Promise (<anonymous>)
    at updateCookies (axioRequest.js:52:12)
    at axioRequest (axioRequest.js:45:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async http (http.js:4:22)
```

Je n'arrive pas à aller plus loin que ça. Je pensais le remplacer par Educonnect, mais je n'y arrive pas non plus...  

Merci pour ton aide !  

Anas,
